# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building the server
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire source code into the working directory
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js image for the runtime
FROM node:18-slim

# Set the working directory in the runtime image
WORKDIR /app

# Copy the build files from the builder image
COPY --from=builder /app/dist ./dist

# Copy package.json and package-lock.json for production install
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Start the server
CMD ["node", "dist/index.js"]